spring.application.name=test_fee
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vyfiyrpmzvxhfadwtnbu
spring.datasource.password=Oct79SDOWTujZnWB

# Native PostgreSQL SQL Schema Initialization (Without ORM/Hibernate)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Razorpay Configuration
razorpay.key.id=rzp_test_TQtCrKTrktLiwZ
razorpay.key.secret=wvrEs8bf4D35fgv1HJQeujIj
Razorpay_Test_Api_KEY=rzp_test_TQtCrKTrktLiwZ
Razorpay_Test_Api_Secret=wvrEs8bf4D35fgv1HJQeujIj
